config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :newtask
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edittask
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  # strong params

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Fonts -->
   <script src="https://kit.fontawesome.com/788e6b6319.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class= "header">
<h1>Edit Task</h1>
</div>

 <div class="form-container">
  <div class="">
    <%= form_for(@task) do |f| %>
    <%= f.label :title, class: "col-m-4 control-label" %>
    <div >
     <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="">
    <%= f.label :details, class: "col-m-4 control-label" %>
  <div>
    <%= f.text_field :details, class: "form-control" %>
   </div>
  </div>
  <div class= "checkbox">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <div class = "form-button">
    <%= f.submit%>
    <% end %>
  </div>
</div>


<div class= "task-action-container">
  <a><%= link_to "Back to list", tasks_path %></a>
</div>

app/views/tasks/index.html.erb
<div class= "header" >
    <h1>My tasks</h1>
</div>

<div class = "container">
 <ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task) %>
    <% if task.completed %>
      <i class="far fa-check-square"></i>
     <% else  %>
    <i class="far fa-square"></i>
     <% end %>
   </li>
  <% end %>
 </ul>
</div>

<div class = "task-action-container">
  <a><%= link_to "Add a new task", newtask_path %></a>
</div>

app/views/tasks/new.html.erb
<div class ="header">
  <h1>New Task</h1>
</div>

 <div class="form-container">
  <div class="form-group">
    <%= form_for(@task) do |f| %>
    <%= f.label :title, class: "col-m-4 control-label" %>
    <div class= "col-md-8">
     <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, class: "col-m-4 control-label" %>
  <div class= "col-md-8">
    <%= f.text_field :details, class: "form-control" %>
   </div>
  </div>
  <div class= "checkbox">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <div class = "form-button">
    <%= f.submit%>
    <% end %>
  </div>
</div>


<div class="task-action-container">
 <a><%= link_to "Back to list", tasks_path %></a>
</div>

app/views/tasks/show.html.erb
<div class = "header">
    <h1><%= @tasks.title %></h1>
   </div>

<div class ="task-action-container">
<ul>
  <li><%= link_to "Back to list", tasks_path %></li>
  <li><%= link_to "Edit this task", edittask_path %></li>
  <li><%= link_to "Delete this task", destroy_path, method: :delete %></li>
</ul>
</div>